version: "3.7"

services:
  mysql:
    image: mariadb:10.5.8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${GLOBAL_PASSWORD}
      MYSQL_PASSWORD: ${GLOBAL_PASSWORD}
      MYSQL_USER: ${GLOBAL_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql

  mongodb:
          image: mongo:latest
          tty: true
          volumes:
              - ./docker-compose/mongo:/data/db
          container_name: mongodb
          ports:
              - "27017:27017"
          environment:
              - MONGODB_USER=${GLOBAL_USERNAME}
              - MONGODB_PASS=${GLOBAL_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.8.0-management
    hostname: my-rabbit
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-compose/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: ${GLOBAL_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${GLOBAL_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /

  redis:
    image: 'redis:alpine'
    container_name: redis
    environment:
      - REDIS_PASSWORD=${GLOBAL_PASSWORD}
    command: redis-server --requirepass ${GLOBAL_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./docker-compose/redis:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  daemon:
    container_name: daemon
    image: newrelic/php-daemon